---
version: "2"
plugins:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
exclude_patterns:
  - ".circleci/"
  - "scripts/"
  - "projects/demo/"
  - "**/karma.conf.js"
  - "*.json"
  - "*.js"
