---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
    - "**.scss"
    - "**.module"
    - "**.ts"
exclude_paths:
  - scripts
  - projects/demo
